### ISSUE TITLE
最小化到桌面右下角的图标,在win10暗色主题下,太不明显了.

### ISSUE THREAD

**Issue by ClutchBear** [Xiphoray/workingmusic#1]
图标改成亮色一点就好了

**Comment by ClutchBear** [comment]
![image](https://user-images.githubusercontent.com/8079857/44940992-7d2d8600-adc8-11e8-93be-81098f5eae29.png)

**Comment by Xiphoray** [comment]
hhhh
这个当时没注意就弄了个背景透明的图标所以会显示不出来
我有空再改吧hhhhh
谢谢提意见噢。。。
